bytesize transcript pgdb
nf-core/nf-co.re pull request #1527
Opened 2023-01-10 18:42 UTC by FranBonath

2023-03-27 19:52 UTC, Dante-von-Zuben requested changes

2023-03-27 19:52 UTC, Dante-von-Zuben commented on markdown/events/2021/bytesize-30-nf-core-pgdb.md
> +First, what is mass spec, especially bottom up proteomics? In summary, you start by extraction of your sample, and you try to separate the protein from that sample. After some preparation, especially
```suggestion
First, what is mass spec, especially bottom up proteomics? In summary, you start by extraction of your sample, and you try to separate the protein from that sample. After some preparation, especially digestion, you convert that into peptides. Then there is mainly two instruments that give you finally millions of mass spectra. Each spectra corresponds to a peptide. All those spectra are a relation between a mass and an intensity for each mass and these fragments of that particular peptide, correspond to one of each peak in the mass spectra. Until that you have the analytical part, the instrument part, but then is when you have bioinformatic tools that need to first take this result from the mass spectrometer, the spectra you need to assign to each of these spectrum peptide with some sort of scoring system there is multiple ones. Then when you have a lease of peptide, you need to infer which protein is the one you are interested in for biology. Finally, you need to do the quantitation of the proteins, how much of that particular protein is in the sample. This is a summary, what bottom up mass spectrometry is. Mainly we'll be talking about this part, what we have done in this part.
```

2023-03-27 19:52 UTC, Dante-von-Zuben commented on markdown/events/2021/bytesize-30-nf-core-pgdb.md
> +As you can see, there is multiple steps if you want to build a proteomics database. Multiple steps to finally have a proteomics database, including the last step, which is a decoy generating step whe
```suggestion
As you can see, there is multiple steps if you want to build a proteomics database. Multiple steps are involved to finally have a proteomics database, including the last step, which is a decoy generating step where you take the target database or the sequence database, and then you attach to the database the decoy generation for the peptide identification steps to a computed FDR score for each peptide. First, before any development related to Nextflow or nf-core, we developed a tool in Python that does the simple steps, like for example, performing the translation from the genome transcript into the protein databases. For example, for pseudogenes, or non-coding RNA, and so on. Or for the most common mutations, databases like COSMIC or cBioPortal that translate that into protein databases. Also simple algorithms inside to generate the decoy sequence for large proteomics databases, or for removing stop calls and so on. This is really important for proteomics. I will not go into in detail, but mainly to process the proteomics database. Then that tool enables to do those independent steps.
```

2023-07-06 08:04 UTC, maxulysse approved these changes

2023-07-06 08:19 UTC, maxulysse commented
@nf-core-bot fix linting pretty please :pray:

2023-07-06 08:27 UTC, merged