bytesize transcript coproID
nf-core/nf-co.re pull request #1528
Opened 2023-01-11 10:15 UTC by FranBonath

2023-03-27 15:22 UTC, atrigila requested changes
For Hackaton2023, I reviewed the content of this transcript. The text is correct. I would only suggest one minor correction in a timestamp :)

2023-03-27 15:22 UTC, atrigila commented on markdown/events/2021/bytesize-29-nf-core-coproid.md
> +[11:32](https://youtu.be/gU4jx1pb8Tw&t=692)
```suggestion
[11:39](https://youtu.be/gU4jx1pb8Tw&t=692)
```

2023-03-27 17:28 UTC, mribeirodantas approved these changes

2023-03-27 17:29 UTC, mribeirodantas commented
Great, @atrigila ! Thanks for the contribution 🥳

2023-03-27 20:31 UTC, gleisonm requested changes

2023-03-28 15:28 UTC, FranBonath commented
Hej @gleisonm Thank you very much for your contribution. I know that the changes you requested are more true to the recording than the original transcript, however, these changes were made deliberately to improve readability. Do you think they do change the original meaning of the text?

2023-03-28 15:46 UTC, gleisonm commented
Hi, Franziska, of course no, improve the readability is more important!
Actually i had the same doubt, about that, be true to the recording, or be
more understandable, then a did the changes to know what you think too.
After all, thanks for reaching me 😊.


Em ter., 28 de mar. de 2023 às 12:29, Franziska Bonath <
***@***.***> escreveu:

> Hej @gleisonm <https://github.com/gleisonm> Thank you very much for your
> contribution. I know that the changes you requested are more true to the
> recording than the original transcript, however, these changes were made
> deliberately to improve readability. Do you think they do change the
> original meaning of the text?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/nf-core/nf-co.re/pull/1528#issuecomment-1487118344>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARBCVQG7EFX4HOHTOEASMXTW6L7TZANCNFSM6AAAAAATX3FLME>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-03-28 16:56 UTC, atrigila approved these changes

2023-03-29 13:36 UTC, merged