Update modules to reflect DSL2
nf-core/nf-co.re pull request #1716
Opened 2023-03-28 20:52 UTC by gregorysprenger

Updated modules.md to reflect DSL2 with a warning about the end of life of DSL1. Also added basic information about what DSL means. This is related to issue https://github.com/nf-core/nf-co.re/issues/1631

2023-03-29 01:01 UTC, christopher-hakkaart requested changes

2023-03-29 01:01 UTC, christopher-hakkaart commented on markdown/developers/contributing_to_pipelines.md
> +
```suggestion
```

2023-03-29 01:01 UTC, christopher-hakkaart commented on markdown/developers/contributing_to_pipelines.md
> +
```suggestion
```

2023-03-29 16:56 UTC, gregorysprenger commented on markdown/developers/contributing_to_pipelines.md
> +3. Make the necessary changes / additions on the `dev` branch by using [git checkout](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pul
For additions to a pipeline, you want to clone the repo and use/make changes on the `dev` branch. I think explicitly stating the dev branch will help with issues.

2023-07-06 09:12 UTC, maxulysse commented
overwrite https://github.com/nf-core/nf-co.re/pull/1715

2023-07-06 13:22 UTC, christopher-hakkaart approved these changes
- Made some minor technical edits. Looks good otherwise.

2023-07-06 13:23 UTC, merged