Added event page for ELIXIR Proteomics Community talk
nf-core/nf-co.re pull request #505
Opened 2020-09-22 17:43 UTC by ewels

Also fixed up the readme file a little (new laptop and I'm trying not to install MAMP, so was working through the docker instructions myself).

2020-09-22 17:54 UTC, ewels commented
I couldn't figure out why the event metadata wasn't rendering in the header, then I realised that this was a minor bug that had found its way through after the refactoring of the `parse_md()` function.

Fixed this, plus added a couple of minor tweaks to the output.

2020-09-23 08:27 UTC, mashehu requested changes

2020-09-23 08:27 UTC, mashehu commented on public_html/events.php
> +  echo "HELLLOOWOOWOW";
```suggestion
 
```

2020-09-23 08:30 UTC, mashehu commented
One small change needed, rest looks good. 

Thanks for the mention in the credits 🙂

2020-09-23 10:06 UTC, ewels commented on public_html/events.php
> +  echo "HELLLOOWOOWOW";
Hah, oops! Well spotted 👀 😆

2020-09-23 10:07 UTC, merged